### ISSUE TITLE
Tref

### ISSUE THREAD

**Issue by bxhsort** [hrz2000/FreeEdit#6]
![image](https://github.com/user-attachments/assets/0a6ea69a-b998-4a87-a6ee-e957c7257508)
I'm curious where Tref comes from and how do you get it

**Comment by hrz2000** [comment]
Similar to blip-diffusion, we manually give an additional reference text Tref "shoe" (of course, it is also possible to use Mllm to obtain the subject information from the reference image, we chose the simplest method, i.e. directly give it artificially), which is used to extract the visual features related to the subject.

**Comment by bxhsort** [comment]
> Similar to blip-diffusion, we manually give an additional reference text Tref "shoe" (of course, it is also possible to use Mllm to obtain the subject information from the reference image, we chose the simplest method, i.e. directly give it artificially), which is used to extract the visual features related to the subject.
Thank you. I have a few questions.
1. If you do not choose to add it will have a great impact on the performance of the model?
2. How do learnable vectors align with the dimensions of T when considering only shoes? Is it the 768 output of CLIP? Is the Enc of the image CLIP

**Comment by hrz2000** [comment]
1. no, because in our experience with debugging on blip-diffusion, the features extracted with a suitable Tref are able to focus more on the subject.
2. The learnable vectors are concated with the Tref text embedding. Prior to this operation, their feature dimensions are consistent, and if I remember correctly, the feature dimensions of both of them were themselves identical.(We haven't changed this operation too much, you can refer to the diffusers implementation of blip-diffusion for more detail)

**Comment by bxhsort** [comment]
> 2\. The learnable vectors are concated with the Tref text embedding. Prior to this operation, their feature dimensions are consistent, and if I remember correctly, the feature dimensions of both of them were themselves identical.(We haven't changed this operation too much, you can refer to the diffusers implementation of blip-diffusion for more detail)
Thank you.
